CREATE TABLE public.players (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), token uuid NOT NULL DEFAULT gen_random_uuid(), name text NOT NULL, score integer NOT NULL DEFAULT 0, dare_key text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT(id,name,score) ON public.players TO anon, authenticated;
GRANT ALL ON public.players TO service_role;
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public leaderboard" ON public.players FOR SELECT TO anon, authenticated USING (true);
CREATE TABLE public.answers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), player_id uuid NOT NULL REFERENCES public.players(id) ON DELETE CASCADE, qkey text NOT NULL, points integer NOT NULL, UNIQUE(player_id,qkey));
GRANT ALL ON public.answers TO service_role;
ALTER TABLE public.answers ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.game_state (id integer PRIMARY KEY DEFAULT 1, unlocked text[] NOT NULL DEFAULT ARRAY['crossword']::text[], updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.game_state TO anon,authenticated;
GRANT ALL ON public.game_state TO service_role;
ALTER TABLE public.game_state ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public round status" ON public.game_state FOR SELECT TO anon,authenticated USING (true);
CREATE FUNCTION public.add_answer_score() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN UPDATE public.players SET score=score+NEW.points WHERE id=NEW.player_id; RETURN NEW; END $$;
CREATE TRIGGER answer_score AFTER INSERT ON public.answers FOR EACH ROW EXECUTE FUNCTION public.add_answer_score();
CREATE FUNCTION public.party_join(player_name text, dare_keys text[]) RETURNS TABLE(id uuid,token uuid,name text,dare_key text) LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE selected_dare text; BEGIN PERFORM pg_advisory_xact_lock(761398); SELECT d INTO selected_dare FROM unnest(dare_keys) d ORDER BY (SELECT count(*) FROM public.players p WHERE p.dare_key=d),random() LIMIT 1; RETURN QUERY INSERT INTO public.players(name,dare_key) VALUES (player_name,selected_dare) RETURNING players.id,players.token,players.name,players.dare_key; END $$;
REVOKE ALL ON FUNCTION public.party_join(text,text[]) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.party_join(text,text[]) TO service_role;
REVOKE ALL ON FUNCTION public.add_answer_score() FROM PUBLIC,anon,authenticated;
ALTER PUBLICATION supabase_realtime ADD TABLE public.players;
ALTER PUBLICATION supabase_realtime ADD TABLE public.game_state;